### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by viniciuschiele** [lgiordani/postage#2]
Do you have plans to implement connection pooling to the producer?

I have applications that sends hundreds messages per sec and I can't create and destroy a connection for every message.

Thanks!

**Comment by lgiordani** [comment]
Thank you for the question. The connection is created in the Producer `__init__()` method, so there is no need to create and destroy the connection for every message. I usually instance one or more producers when booting the application and the reuse them for its whole life.

However, I suspect I am missing your use case, may you clarify? I am definitely available to change the code to meet performance requirements.

**Comment by viniciuschiele** [comment]
I see two issues using "static" producers:

First one, each Producer has one channel, at least in theory the same channel instance can't be used by multiple threads, so we might have unexpected errors and I would like to avoid locks.

Second one, what happens if this connection died for some reason like network issues? How would you reconnect it?

Cheers

**Comment by lgiordani** [comment]
Interesting problems! I did not think about such issues.
Do you have suggestions? In the meantime I start considering the issue.
Thanks a lot

**Comment by viniciuschiele** [comment]
To the Producer, each 'publish' would have to take one connection and one channel from the pool and release them after sending the message. If an error occurs sending the message the current connection must be destroied and another one is taken from the pool.

To the Consumer is a bit harder because each consumer has its connection and channel for its whole life. You would have to have a wrapped connection class for the connection and listening to the close/exception event to reconnect.

It is not an easy implementation, I did it for C# + ActiveMQ and it took me a lot of time.

**Comment by lgiordani** [comment]
As you noticed, the project is basically abandoned. I'm not actively working with RMQ anymore, so I am working on other projects. I'm sorry, but I will close this issue at least until I resume the project. Thanks anyway for the contribution!
