### ISSUE TITLE
Please, consider using BSD license instead of GPL

### ISSUE THREAD

**Issue by frol** [lgiordani/postage#3]
I would love to try and use postage in my personal projects (open-source non-GPL) as well as in commercial projects I work on, but GPL license allows me neither publishing my open-source projects with MIT license (which I personally prefer using) nor using postman in closed-source products.

Pika is licensed under BSD 3-clause license, this is why I ask to use BSD license for postage, yet MIT, Apache, or even LGPL would work for me.

Thank you for your work!

**Comment by lgiordani** [comment]
Thank you for your  suggestion. Postage is going through a major refactoring under the umbrella of the project PostageMQ, that you can find here https://github.com/postagemq. The Python code (as well as other future porting) will be released under LGPL to allow broader adoption. You may expect the initial code to be released in a month or two.

Thank you for your support!
